FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY order/package.json ./order/package.json
COPY worker/package.json ./worker/package.json
COPY packages/contracts/package.json ./packages/contracts/package.json

RUN pnpm install --frozen-lockfile

COPY packages/contracts ./packages/contracts
COPY worker ./worker

RUN pnpm --filter @orderflow/contracts build

WORKDIR /app/worker

CMD ["pnpm", "dev"]
