import "dotenv/config";

import { defineConfig } from "drizzle-kit";

// Read the database connection from the service environment.
//
// The Order API owns its database configuration, so DATABASE_URL belongs
// to apps/order-api/.env.example rather than the monorepo root.
const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL is not defined");
}

export default defineConfig({
  // Drizzle schema owned by the Order API.
  schema: "./src/db/schema/index.ts",

  // Database migrations owned and generated by the Order API.
  out: "./src/db/migrations",

  // OrderFlow currently uses PostgreSQL.
  dialect: "postgresql",

  // Drizzle Kit uses this connection when generating and applying migrations.
  dbCredentials: {
    url: databaseUrl,
  },

  // Fail on potentially unsafe or ambiguous migration changes.
  strict: true,

  // Provide additional information during migration/configuration operations.
  verbose: true,
});
