// order-api/src/products/product.validation.ts

import { z } from "zod";

// -----------------------------------------------------------------------------
// Product ID
// -----------------------------------------------------------------------------

/**
 * Validates a product UUID.
 *
 * Product IDs are generated by PostgreSQL and exposed by the API.
 */
export const productIdSchema = z.uuid();

// -----------------------------------------------------------------------------
// Get product by ID
// -----------------------------------------------------------------------------

/**
 * Validates the route parameters for:
 *
 * GET /products/:productId
 */
export const getProductParamsSchema = z.object({
  productId: productIdSchema,
});

// -----------------------------------------------------------------------------
// Product response
// -----------------------------------------------------------------------------

/**
 * Schema representing a product returned by the API.
 *
 * Price is represented in the smallest currency unit.
 *
 * Example:
 * $1,999.00 → 199900
 */
export const productSchema = z.object({
  id: productIdSchema,
  name: z.string().min(1),
  description: z.string().min(1),
  price: z.number().int().nonnegative(),
  image: z.string().min(1),
  active: z.boolean(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

/**
 * Schema representing the response from:
 *
 * GET /products
 */
export const productListResponseSchema = z.object({
  products: z.array(productSchema),
});
