// order-api/src/orders/order.validation.ts

import { z } from "zod";

// -----------------------------------------------------------------------------
// Order ID
// -----------------------------------------------------------------------------

/**
 * Validates an order UUID.
 *
 * Order IDs are generated by PostgreSQL.
 */
export const orderIdSchema = z.uuid();

// -----------------------------------------------------------------------------
// Order item
// -----------------------------------------------------------------------------

/**
 * Validates one item submitted when creating an order.
 *
 * The client only provides:
 * - productId
 * - quantity
 *
 * Product name and price are resolved by the backend.
 */
export const createOrderItemSchema = z.object({
  /**
   * UUID of the product being ordered.
   */
  productId: z.uuid(),

  /**
   * Number of units requested.
   *
   * Must be a positive integer.
   */
  quantity: z.number().int().positive(),
});

// -----------------------------------------------------------------------------
// Create order
// -----------------------------------------------------------------------------

/**
 * Validates the request body for:
 *
 * POST /orders
 *
 * Example:
 *
 * {
 *   "customerName": "Nikhil",
 *   "items": [
 *     {
 *       "productId": "8b7e6f2a-4c91-4e3d-9a72-1f5c8d6b1234",
 *       "quantity": 1
 *     }
 *   ]
 * }
 */
export const createOrderSchema = z.object({
  /**
   * Customer placing the order.
   */
  customerName: z.string().trim().min(1, "Customer name is required"),

  /**
   * Products included in the order.
   *
   * An order must contain at least one item.
   */
  items: z
    .array(createOrderItemSchema)
    .min(1, "Order must contain at least one item"),
});

// -----------------------------------------------------------------------------
// Get order
// -----------------------------------------------------------------------------

/**
 * Validates the route parameters for:
 *
 * GET /orders/:orderId
 */
export const getOrderParamsSchema = z.object({
  orderId: orderIdSchema,
});

// -----------------------------------------------------------------------------
// Order list
// -----------------------------------------------------------------------------

/**
 * Validates query parameters for:
 *
 * GET /orders
 *
 * Pagination can be added later without changing the create-order
 * validation contract.
 */
export const getOrdersQuerySchema = z.object({
  page: z.coerce.number().int().positive().optional(),

  limit: z.coerce.number().int().positive().max(100).optional(),
});
